[pyprland]
plugins = [
  "scratchpads",
]

[scratchpads.term]
animation = "fromBottom"
command = "kitty"
class = "kitty"
size = "43% 30%"

[scratchpads.volume]
animation = "fromRight"
command = "pavucontrol"
class = "pavucontrol"
size = "40% 60%"


